"""
LaTeX templates for CONSORT 2025 clinical trial reports.

Provides the document preamble, section structure, and a CONSORT
compliance checklist table template.
"""

from __future__ import annotations

# ── Document preamble ───────────────────────────────────────────────────

PREAMBLE = r"""
\documentclass[12pt,a4paper]{article}

% --- Encoding & fonts ---
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

% --- Page geometry ---
\usepackage[margin=2.5cm]{geometry}

% --- Typography ---
\usepackage{microtype}
\usepackage{setspace}
\onehalfspacing

% --- Tables ---
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}

% --- Graphics & floats ---
\usepackage{graphicx}
\usepackage{float}

% --- References & links ---
\usepackage[hidelinks]{hyperref}
\usepackage{cleveref}

% --- Maths ---
\usepackage{amsmath}

% --- Lists ---
\usepackage{enumitem}

% --- Headers ---
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\leftmark}
\fancyhead[R]{\thepage}

% --- Title ---
\title{CONSORT 2025 Clinical Trial Report}
\author{Generated by CliniRepGen Deep Research Agent}
\date{\today}
""".strip()


# ── Begin / end document ────────────────────────────────────────────────

BEGIN_DOCUMENT = r"""
\begin{document}
\maketitle
\tableofcontents
\newpage
""".strip()

END_DOCUMENT = r"""
\end{document}
""".strip()


# ── Section mapping ─────────────────────────────────────────────────────
# Maps CONSORT section names to LaTeX section commands.

SECTION_COMMANDS: dict[str, str] = {
    "Title and abstract": r"\section{Title and Abstract}",
    "Open science": r"\section{Open Science}",
    "Introduction": r"\section{Introduction}",
    "Methods": r"\section{Methods}",
    "Results": r"\section{Results}",
    "Discussion": r"\section{Discussion}",
}


# ── CONSORT compliance checklist table ──────────────────────────────────

CONSORT_TABLE_HEADER = r"""
\newpage
\section*{CONSORT 2025 Compliance Checklist}

\begin{longtable}{p{1cm} p{3cm} p{4cm} p{6cm} p{1.5cm}}
\toprule
\textbf{Item} & \textbf{Section} & \textbf{Topic} & \textbf{Description} & \textbf{Page} \\
\midrule
\endhead
""".strip()

CONSORT_TABLE_ROW = r"{item_id} & {section} & {topic} & {description} & \pageref{{sec:{item_id}}} \\"

CONSORT_TABLE_FOOTER = r"""
\bottomrule
\end{longtable}
""".strip()
